### ISSUE TITLE
TL;DR should include original message link

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/tldr#5]
At present, the TL;DR feature lacks a reference to the specific message being summarized. To improve the clarity and usefulness of TL;DR summaries, it would be beneficial to include a link to the original message within the TL;DR output. This addition would provide users with easy access to the complete context and facilitate efficient navigation within the conversation.

**Comment by jjoeldaniel** [comment]
TL;DR: We should include a link to the original message for better context and navigation.
