### ISSUE TITLE
Handle undefined PaLM responses

### ISSUE THREAD

**Issue by jjoeldaniel** [acmcsufoss/tldr#6]
PaLM will occasionally fail and return the following response:

![Error: Cannot Read properties of undefined \(reading '0'\)](https://github.com/acmcsufoss/tldr/assets/100006388/beb02418-9e27-4bae-8955-363d0701ea95)

**Comment by EthanThatOneKid** [comment]
The PaLM module occasionally encounters failures, resulting in an error response as follows:

![Error: Cannot Read properties of undefined (reading '0')](https://user-images.githubusercontent.com/100006388/244610637-beb02418-9e27-4bae-8955-363d0701ea95.png)

Upon analysis, it appears that this error occurs when the PaLM response lacks any messages precisely at the indicated line of code:

<https://github.com/acmcsufoss/tldr/blob/ae68b005516a1af948b9d228b91d2a35b371dbf2/main.ts#L84>

To address this issue effectively, it is advised to implement an appropriate error handling mechanism. This can involve gracefully handling the error by displaying an ephemeral message or providing a more informative error message, which would enhance the overall user experience and maintain the module's reliability.

Furthermore, for future enhancements, it is worth considering the incorporation of a robust retry strategy utilizing the [`retry`](https://deno.land/std/async/retry.ts?s=retry) function, leveraging the recommended [`retryPolicy`](https://github.com/googleapis/googleapis/blob/77c99e43177c76ae1c1edacee7b6ac4e35a42f3d/google/ai/generativelanguage/v1main/v1beta2/generativeai_grpc_service_config.json#L16) defined in the Google APIs. This approach would ensure resilience in the face of transient failures, providing a more reliable and seamless user experience.

**Comment by EthanThatOneKid** [comment]
An appropriate error message should be returned within the Discord integration response object if an error message is caught during the `tldr` process.

**Comment by EthanThatOneKid** [comment]
See: <https://github.com/acmcsufoss/tldr/pull/15#issuecomment-1736821608>.
